### ISSUE TITLE
MIS not supported

### ISSUE THREAD

**Issue by F5OEO** [daniestevez/dvb-gse#6]
Multiple Input Stream is not supported yet. However, some equipment indicates MIS even with a single stream. BBFrame parsing should be fine by bypassing the strict condition of SIS. The only drawback is if we have concurent IP of different interfaces which are in collision. Adding a filter on ISI could be a solution and send streams to several tun interfaces.
 
Proposal : Remove https://github.com/daniestevez/dvb-gse/blob/e61d18e74166172a5f5ae2aaf2da668c3e27cc42/src/bbframe.rs#L138

**Comment by daniestevez** [comment]
I decided not to support MIS initially because it wasn't needed in my use case and it is somewhat more tricky to support (a different GSE defragmentation context per stream is needed, streams might be of different types, the user could want to classify each stream to a different output...)

I'm thinking about adding an `--isi` option to `dvb-gse` so that a MIS signal can be processed. If the user specifies `--isi n`, then the signal will be expected to be MIS and only ISI `n` will be processed. If `--isi` is not specified, then the signal will be expected to be SIS as it currently happens. Would this be a good solution for your use case?

**Comment by F5OEO** [comment]
Yes, a nice solution to show a "false" MIS as SIS.

**Comment by daniestevez** [comment]
I have made the required changes to support MIS mode by looking at a single ISI specified by the user. This is in the PR #9. Can you test this with your MIS transmitter before I merge it?

**Comment by F5OEO** [comment]
Confirm working.

**Comment by Dorfmaan** [comment]
Hello,
I would like to congratulate you on your really great efforts and the support option for MIS.
Is there any possibility for input signal to be used RAW I/Q file or or to be used SDR receiver?

Best Regards!

**Comment by daniestevez** [comment]
> Is there any possibility for input signal to be used RAW I/Q file or or to be used SDR receiver?

You can probably use [gr-dvbs2rx](https://github.com/igorauad/gr-dvbs2rx), [leandvb](https://www.pabr.org/radio/leandvb/leandvb.en.html), or other SDR DVB-S2 decoder to output BBFRAMEs to dvb-gse (this application). You could even keep everything inside of GNU Radio by using [gr-dvbgse](https://github.com/drmpeg/gr-dvbgse) for reception, unless dvb-gse gives you some extra features that you need.

Demodulation of DVB-S2 is out of the scope of dvb-gse.
